### ISSUE TITLE
Clearing flashes on redirect

### ISSUE THREAD

**Issue by miracle2k** [danielfm/django-flash#5]
I just spent some time tracking down a bug that ultimately turned out to be me redirecting to a URL without a slash, in effect resulting in two redirects, and the flash never making it to the final page.

This makes we wonder though - it seems wrong that this is happening at all - I would think that those redirects should be just skipped. Now as far as I can tell about how django-flash works, there doesn't seem to be a good way to do this though, since the flash is cleared on an incoming request and obviously, django-flash wouldn't know what the request is actually doing.

Still.. couldn't the flash simply be cleared on access? Not sure if there are other solutions...

**Comment by danielfm** [comment]
Yes, something has to be done about that. I'll see what I can do.

**Comment by danielfm** [comment]
Oh, and clear the flash on access doesn't seem to be good thing to do, IMO.

First, because it goes against the project's intent, which is to provide a flash implementation that works similar to Rails'.

The second reason is that the flash (which is a dict of some kind) may be accessed several times during a complex request/response cycle, by several parties. Thus, there's no way of knowing the right time to clear the messages. That's why I like the way Rails handles the flash in the first place: you know exactly how and when your messages will be removed. No black magic. :-)

Of course, as you (as several others) pointed out, Django-Flash doesn't play nice with HTTP redirects yet. But I'll see what I can do to make things work more smoothly.

**Comment by danielfm** [comment]
Please take a look on [my last commit](http://github.com/danielfm/django-flash/commit/9c9d7cf719440e0388694bc3692c8c9ac21aaa85), in which I've done some work to better integrate the FlashMiddleware with CommonMiddleware. This also should work regardless you place the CommonMiddleware before or after the FlashMiddleware.

I'll wait you guys test those changes before I release a new version.

**Comment by miracle2k** [comment]
Well, I can report that the scenario I described above now works for me (redirect without a slash). Thanks.

**Comment by danielfm** [comment]
Thanks for your feedback! A new version will be released shortly.
